#pragma once

enum TiXmlError {
	TIXML_NO_ERROR = 0,
	TIXML_ERROR,
	TIXML_ERROR_OPENING_FILE,
	TIXML_ERROR_PARSING_ELEMENT,
	TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME,
	TIXML_ERROR_READING_ELEMENT_VALUE,
	TIXML_ERROR_READING_ATTRIBUTES,
	TIXML_ERROR_PARSING_EMPTY,
	TIXML_ERROR_READING_END_TAG,
	TIXML_ERROR_PARSING_UNKNOWN,
	TIXML_ERROR_PARSING_COMMENT,
	TIXML_ERROR_PARSING_DECLARATION,
	TIXML_ERROR_DOCUMENT_EMPTY,
	TIXML_ERROR_EMBEDDED_NULL,
	TIXML_ERROR_PARSING_CDATA,
	TIXML_ERROR_DOCUMENT_TOP_ONLY,

	TIXML_ERROR_STRING_COUNT
};
