# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Export')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Export')
    _Export = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Export', [dirname(__file__)])
        except ImportError:
            import _Export
            return _Export
        try:
            _mod = imp.load_module('_Export', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Export = swig_import_helper()
    del swig_import_helper
else:
    import _Export
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Export.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _Export.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Export.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Export.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Export.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Export.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Export.SwigPyIterator_copy(self)

    def next(self):
        return _Export.SwigPyIterator_next(self)

    def __next__(self):
        return _Export.SwigPyIterator___next__(self)

    def previous(self):
        return _Export.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Export.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Export.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Export.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Export.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Export.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Export.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Export.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Export.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class CExporter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CExporter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CExporter, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _Export.new_CExporter()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Export.delete_CExporter
    __del__ = lambda self: None

    def OutputDomainToIGES(self, fileName, Domain):
        return _Export.CExporter_OutputDomainToIGES(self, fileName, Domain)

    def OutputDomainToSTEP(self, fileName, Domain):
        return _Export.CExporter_OutputDomainToSTEP(self, fileName, Domain)

    def OutputTextileToIGES(self, *args):
        return _Export.CExporter_OutputTextileToIGES(self, *args)

    def OutputTextileToSTEP(self, *args):
        return _Export.CExporter_OutputTextileToSTEP(self, *args)

    def GetExportDomain(self):
        return _Export.CExporter_GetExportDomain(self)

    def GetSubtractYarns(self):
        return _Export.CExporter_GetSubtractYarns(self)

    def SetExportDomain(self, bExportDomain):
        return _Export.CExporter_SetExportDomain(self, bExportDomain)

    def SetSubtractYarns(self, bSubtractYarns):
        return _Export.CExporter_SetSubtractYarns(self, bSubtractYarns)
CExporter_swigregister = _Export.CExporter_swigregister
CExporter_swigregister(CExporter)

# This file is compatible with both classic and new-style classes.


